name: pulse_frontend
description: Task Management Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  intl: any
  freezed: ^3.0.6
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  lucide_icons_flutter: ^3.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/pulse_loading.gif